// Define your flat list of targets here
// Example:
// window.PM_ITEMS = ["The next time I …", "…"];

// Default items (English)
window.PM_ITEMS = [
  "The next time I see a pet or animal",
  "The next time I look at my face in the mirror",
  "The next time I turn on a light",
  "The next time I see a flower",
  "The next time I write anything down",
  "The next time I feel pain",
  "The next time I hear someone say my name",
  "The next time I drink something",
  "The next time I see a traffic light",
  "The next time I hear music",
  "The next time I throw something away",
  "The next time I hear laughter",
  "The next time I turn on a TV or radio",
  "The next time I see a vegetable",
  "The next time I see a red car",
  "The next time I handle money",
  "The next time I read something besides this list",
  "The next time I check the time",
  "The next time I notice myself daydreaming",
  "The next time I hear a phone ring",
  "The next time I open a door",
  "The next time I see a bird",
  "The next time I use the bathroom after noon",
  "The next time I see the stars",
  "The next time I put a key in a lock",
  "The next time I see an advertisement",
  "The next time I eat anything after breakfast",
  "The next time I see a bicycle",
  "The next time I tie my shoes",
  "The next time I wash my hands",
  "The next time I take a seat",
  "The next time I stand up",
  "The next time I plug in a cable",
  "The next time I receive a notification",
  "The next time I see the moon",
  "The next time I hear a siren",
  "The next time I take a sip of water",
  "The next time I open a browser tab",
  "The next time I close a window",
  "The next time I feel the wind",
  "The next time I see my reflection",
  "The next time I unlock my phone",
  "The next time I charge my phone",
  "The next time I stretch",
  "The next time I yawn",
  "The next time I sneeze",
  "The next time I cough",
  "The next time I laugh",
  "The next time I clap",
  "The next time I snap my fingers",
  "The next time I use a remote",
  "The next time I switch tabs",
  "The next time I hear a bird singing",
  "The next time I smell coffee",
  "The next time I boil water",
  "The next time I set a timer",
  "The next time I touch a doorknob",
  "The next time I lock a door",
  "The next time I adjust the volume",
  "The next time I put on headphones",
  "The next time I take off headphones",
  "The next time I sign my name",
  "The next time I send a message",
  "The next time I receive a message",
  "The next time I scroll to the bottom of a page",
  "The next time I scroll to the top",
  "The next time I bookmark a page",
  "The next time I like a post",
  "The next time I see a stop sign",
  "The next time I cross a street",
  "The next time I wash a dish",
  "The next time I turn a page",
  "The next time I see a cloud shaped like something",
  "The next time I put on shoes",
  "The next time I take off shoes",
  "The next time I zip a zipper",
  "The next time I button a button",
  "The next time I tie a knot",
  "The next time I fold laundry",
  "The next time I hang a towel",
  "The next time I water a plant",
  "The next time I see a house number",
  "The next time I hear a notification chime",
  "The next time I open the fridge",
  "The next time I close the fridge",
  "The next time I preheat the oven",
  "The next time I take out the trash",
  "The next time I recycle something",
  "The next time I use a password",
  "The next time I plug in a charger",
  "The next time I unmute the sound",
  "The next time I mute the sound",
  "The next time I take a screenshot",
  "The next time I copy text",
  "The next time I paste text",
  "The next time I rename a file",
  "The next time I create a folder",
  "The next time I open settings",
  "The next time I check the weather",
  "The next time I see a calendar",
  "The next time I hear an alarm",
  "The next time I flip a light switch",
  "The next time I look at the sky"
];

// Optional UI translations for default items only (user items are not translated)
// Map: { langCode: { englishItem: translatedItem } }
window.PM_TRANSLATIONS = window.PM_TRANSLATIONS || {};
window.PM_TRANSLATIONS.et = Object.assign({}, window.PM_TRANSLATIONS.et, {
  "The next time I see a pet or animal": "Järgmine kord, kui näen lemmiklooma või looma",
  "The next time I look at my face in the mirror": "Järgmine kord, kui vaatan peeglist oma nägu",
  "The next time I turn on a light": "Järgmine kord, kui lülitan tule põlema",
  "The next time I see a flower": "Järgmine kord, kui näen lille",
  "The next time I write anything down": "Järgmine kord, kui kirjutan midagi üles",
  "The next time I feel pain": "Järgmine kord, kui tunnen valu",
  "The next time I hear someone say my name": "Järgmine kord, kui kuulen kedagi ütlemas minu nime",
  "The next time I drink something": "Järgmine kord, kui joon midagi",
  "The next time I see a traffic light": "Järgmine kord, kui näen foorituld",
  "The next time I hear music": "Järgmine kord, kui kuulen muusikat",
  "The next time I throw something away": "Järgmine kord, kui viskan midagi ära",
  "The next time I hear laughter": "Järgmine kord, kui kuulen naeru",
  "The next time I turn on a TV or radio": "Järgmine kord, kui lülitan sisse televiisori või raadio",
  "The next time I see a vegetable": "Järgmine kord, kui näen köögivilja",
  "The next time I see a red car": "Järgmine kord, kui näen punast autot",
  "The next time I handle money": "Järgmine kord, kui käsitsen raha",
  "The next time I read something besides this list": "Järgmine kord, kui loen midagi peale selle nimekirja",
  "The next time I check the time": "Järgmine kord, kui vaatan kella",
  "The next time I notice myself daydreaming": "Järgmine kord, kui märkan end unistamas",
  "The next time I hear a phone ring": "Järgmine kord, kui kuulen telefoni helisemas",
  "The next time I open a door": "Järgmine kord, kui avan ukse",
  "The next time I see a bird": "Järgmine kord, kui näen lindu",
  "The next time I use the bathroom after noon": "Järgmine kord, kui kasutan tualetti pärast lõunat",
  "The next time I see the stars": "Järgmine kord, kui näen tähti",
  "The next time I put a key in a lock": "Järgmine kord, kui panen võtme lukuauku",
  "The next time I see an advertisement": "Järgmine kord, kui näen reklaami",
  "The next time I eat anything after breakfast": "Järgmine kord, kui söön midagi pärast hommikusööki",
  "The next time I see a bicycle": "Järgmine kord, kui näen jalgratast",
  "The next time I tie my shoes": "Järgmine kord, kui seon jalanõud",
  "The next time I wash my hands": "Järgmine kord, kui pesen käsi",
  "The next time I take a seat": "Järgmine kord, kui istun",
  "The next time I stand up": "Järgmine kord, kui tõusen püsti",
  "The next time I plug in a cable": "Järgmine kord, kui ühendan kaabli",
  "The next time I receive a notification": "Järgmine kord, kui saan teavituse",
  "The next time I see the moon": "Järgmine kord, kui näen kuud",
  "The next time I hear a siren": "Järgmine kord, kui kuulen sireeni",
  "The next time I take a sip of water": "Järgmine kord, kui võtan lonksu vett",
  "The next time I open a browser tab": "Järgmine kord, kui avan brauseri vahelehe",
  "The next time I close a window": "Järgmine kord, kui sulgen akna",
  "The next time I feel the wind": "Järgmine kord, kui tunnen tuult",
  "The next time I see my reflection": "Järgmine kord, kui näen oma peegeldust",
  "The next time I unlock my phone": "Järgmine kord, kui avan oma telefoni",
  "The next time I charge my phone": "Järgmine kord, kui laen oma telefoni",
  "The next time I stretch": "Järgmine kord, kui sirutan end",
  "The next time I yawn": "Järgmine kord, kui haigutan",
  "The next time I sneeze": "Järgmine kord, kui aevastan",
  "The next time I cough": "Järgmine kord, kui köhin",
  "The next time I laugh": "Järgmine kord, kui naeran",
  "The next time I clap": "Järgmine kord, kui plaksutan",
  "The next time I snap my fingers": "Järgmine kord, kui nipsutan sõrmi",
  "The next time I use a remote": "Järgmine kord, kui kasutan pulti",
  "The next time I switch tabs": "Järgmine kord, kui vahetan vahelehte",
  "The next time I hear a bird singing": "Järgmine kord, kui kuulen linnulaulu",
  "The next time I smell coffee": "Järgmine kord, kui tunnen kohvilõhna",
  "The next time I boil water": "Järgmine kord, kui keedan vett",
  "The next time I set a timer": "Järgmine kord, kui panen taimeri",
  "The next time I touch a doorknob": "Järgmine kord, kui puudutan uksekäepidet",
  "The next time I lock a door": "Järgmine kord, kui lukustan ukse",
  "The next time I adjust the volume": "Järgmine kord, kui reguleerin helitugevust",
  "The next time I put on headphones": "Järgmine kord, kui panen kõrvaklapid pähe",
  "The next time I take off headphones": "Järgmine kord, kui võtan kõrvaklapid peast",
  "The next time I sign my name": "Järgmine kord, kui kirjutan oma nime",
  "The next time I send a message": "Järgmine kord, kui saadan sõnumi",
  "The next time I receive a message": "Järgmine kord, kui saan sõnumi",
  "The next time I scroll to the bottom of a page": "Järgmine kord, kui kerin lehe lõppu",
  "The next time I scroll to the top": "Järgmine kord, kui kerin lehe algusesse",
  "The next time I bookmark a page": "Järgmine kord, kui lisan lehe järjehoidjatesse",
  "The next time I like a post": "Järgmine kord, kui laigin postitust",
  "The next time I see a stop sign": "Järgmine kord, kui näen stoppmärki",
  "The next time I cross a street": "Järgmine kord, kui ületan tänavat",
  "The next time I wash a dish": "Järgmine kord, kui pesen nõu",
  "The next time I turn a page": "Järgmine kord, kui keeran lehte",
  "The next time I see a cloud shaped like something": "Järgmine kord, kui näen millegi kujuga pilve",
  "The next time I put on shoes": "Järgmine kord, kui panen jalanõud jalga",
  "The next time I take off shoes": "Järgmine kord, kui võtan jalanõud ära",
  "The next time I zip a zipper": "Järgmine kord, kui tõmban luku kinni",
  "The next time I button a button": "Järgmine kord, kui kinnitan nööbi",
  "The next time I tie a knot": "Järgmine kord, kui seon sõlme",
  "The next time I fold laundry": "Järgmine kord, kui voltin pesu",
  "The next time I hang a towel": "Järgmine kord, kui riputan rätiku",
  "The next time I water a plant": "Järgmine kord, kui kastan taime",
  "The next time I see a house number": "Järgmine kord, kui näen majanumbrit",
  "The next time I hear a notification chime": "Järgmine kord, kui kuulen teavituse heli",
  "The next time I open the fridge": "Järgmine kord, kui avan külmkapi",
  "The next time I close the fridge": "Järgmine kord, kui sulgen külmkapi",
  "The next time I preheat the oven": "Järgmine kord, kui soojendan ahju",
  "The next time I take out the trash": "Järgmine kord, kui viin prügi välja",
  "The next time I recycle something": "Järgmine kord, kui taaskasutan midagi",
  "The next time I use a password": "Järgmine kord, kui kasutan parooli",
  "The next time I plug in a charger": "Järgmine kord, kui ühendan laadija",
  "The next time I unmute the sound": "Järgmine kord, kui võtan heli summutusest",
  "The next time I mute the sound": "Järgmine kord, kui summutan heli",
  "The next time I take a screenshot": "Järgmine kord, kui teen ekraanipildi",
  "The next time I copy text": "Järgmine kord, kui kopeerin teksti",
  "The next time I paste text": "Järgmine kord, kui kleebin teksti",
  "The next time I rename a file": "Järgmine kord, kui nimetan faili ümber",
  "The next time I create a folder": "Järgmine kord, kui loon kausta",
  "The next time I open settings": "Järgmine kord, kui avan seaded",
  "The next time I check the weather": "Järgmine kord, kui vaatan ilma",
  "The next time I see a calendar": "Järgmine kord, kui näen kalendrit",
  "The next time I hear an alarm": "Järgmine kord, kui kuulen äratust",
  "The next time I flip a light switch": "Järgmine kord, kui vajutan valguslülitit",
  "The next time I look at the sky": "Järgmine kord, kui vaatan taevast"
});
