// System defaults in a single, normalized structure.
// One source of truth: stable id + English + Estonian.
// Add/edit items here. User items are separate and never translated.
window.PM_DEFAULTS = [
  { id: 'd001', en: "The next time I see a pet or animal", et: "Järgmine kord, kui näen lemmiklooma või looma" },
  { id: 'd002', en: "The next time I look at my face in the mirror", et: "Järgmine kord, kui vaatan peeglist oma nägu" },
  { id: 'd003', en: "The next time I turn on a light", et: "Järgmine kord, kui lülitan tule põlema" },
  { id: 'd004', en: "The next time I see a flower", et: "Järgmine kord, kui näen lille" },
  { id: 'd005', en: "The next time I write anything down", et: "Järgmine kord, kui kirjutan midagi üles" },
  { id: 'd006', en: "The next time I feel pain", et: "Järgmine kord, kui tunnen valu" },
  { id: 'd007', en: "The next time I hear someone say my name", et: "Järgmine kord, kui kuulen kedagi ütlemas minu nime" },
  { id: 'd008', en: "The next time I drink something", et: "Järgmine kord, kui joon midagi" },
  { id: 'd009', en: "The next time I see a traffic light", et: "Järgmine kord, kui näen foorituld" },
  { id: 'd010', en: "The next time I hear music", et: "Järgmine kord, kui kuulen muusikat" },
  { id: 'd011', en: "The next time I throw something away", et: "Järgmine kord, kui viskan midagi ära" },
  { id: 'd012', en: "The next time I hear laughter", et: "Järgmine kord, kui kuulen naeru" },
  { id: 'd013', en: "The next time I turn on a TV or radio", et: "Järgmine kord, kui lülitan sisse televiisori või raadio" },
  { id: 'd014', en: "The next time I see a vegetable", et: "Järgmine kord, kui näen köögivilja" },
  { id: 'd015', en: "The next time I see a red car", et: "Järgmine kord, kui näen punast autot" },
  { id: 'd016', en: "The next time I handle money", et: "Järgmine kord, kui käsitsen raha" },
  { id: 'd017', en: "The next time I read something besides this list", et: "Järgmine kord, kui loen midagi peale selle nimekirja" },
  { id: 'd018', en: "The next time I check the time", et: "Järgmine kord, kui vaatan kella" },
  { id: 'd019', en: "The next time I notice myself daydreaming", et: "Järgmine kord, kui märkan end unistamas" },
  { id: 'd020', en: "The next time I hear a phone ring", et: "Järgmine kord, kui kuulen telefoni helisemas" },
  { id: 'd021', en: "The next time I open a door", et: "Järgmine kord, kui avan ukse" },
  { id: 'd022', en: "The next time I see a bird", et: "Järgmine kord, kui näen lindu" },
  { id: 'd023', en: "The next time I use the bathroom after noon", et: "Järgmine kord, kui kasutan tualetti pärast lõunat" },
  { id: 'd024', en: "The next time I see the stars", et: "Järgmine kord, kui näen tähti" },
  { id: 'd025', en: "The next time I put a key in a lock", et: "Järgmine kord, kui panen võtme lukuauku" },
  { id: 'd026', en: "The next time I see an advertisement", et: "Järgmine kord, kui näen reklaami" },
  { id: 'd027', en: "The next time I eat anything after breakfast", et: "Järgmine kord, kui söön midagi pärast hommikusööki" },
  { id: 'd028', en: "The next time I see a bicycle", et: "Järgmine kord, kui näen jalgratast" },
  { id: 'd029', en: "The next time I tie my shoes", et: "Järgmine kord, kui seon jalanõud" },
  { id: 'd030', en: "The next time I wash my hands", et: "Järgmine kord, kui pesen käsi" },
  { id: 'd031', en: "The next time I take a seat", et: "Järgmine kord, kui istun" },
  { id: 'd032', en: "The next time I stand up", et: "Järgmine kord, kui tõusen püsti" },
  { id: 'd033', en: "The next time I plug in a cable", et: "Järgmine kord, kui ühendan kaabli" },
  { id: 'd034', en: "The next time I receive a notification", et: "Järgmine kord, kui saan teavituse" },
  { id: 'd035', en: "The next time I see the moon", et: "Järgmine kord, kui näen kuud" },
  { id: 'd036', en: "The next time I hear a siren", et: "Järgmine kord, kui kuulen sireeni" },
  { id: 'd037', en: "The next time I take a sip of water", et: "Järgmine kord, kui võtan lonksu vett" },
  { id: 'd038', en: "The next time I open a browser tab", et: "Järgmine kord, kui avan brauseri vahelehe" },
  { id: 'd039', en: "The next time I close a window", et: "Järgmine kord, kui sulgen akna" },
  { id: 'd040', en: "The next time I feel the wind", et: "Järgmine kord, kui tunnen tuult" },
  { id: 'd041', en: "The next time I see my reflection", et: "Järgmine kord, kui näen oma peegeldust" },
  { id: 'd042', en: "The next time I unlock my phone", et: "Järgmine kord, kui avan oma telefoni" },
  { id: 'd043', en: "The next time I charge my phone", et: "Järgmine kord, kui laen oma telefoni" },
  { id: 'd044', en: "The next time I stretch", et: "Järgmine kord, kui sirutan end" },
  { id: 'd045', en: "The next time I yawn", et: "Järgmine kord, kui haigutan" },
  { id: 'd046', en: "The next time I sneeze", et: "Järgmine kord, kui aevastan" },
  { id: 'd047', en: "The next time I cough", et: "Järgmine kord, kui köhin" },
  { id: 'd048', en: "The next time I laugh", et: "Järgmine kord, kui naeran" },
  { id: 'd049', en: "The next time I clap", et: "Järgmine kord, kui plaksutan" },
  { id: 'd050', en: "The next time I snap my fingers", et: "Järgmine kord, kui nipsutan sõrmi" },
  { id: 'd051', en: "The next time I use a remote", et: "Järgmine kord, kui kasutan pulti" },
  { id: 'd052', en: "The next time I switch tabs", et: "Järgmine kord, kui vahetan vahelehte" },
  { id: 'd053', en: "The next time I hear a bird singing", et: "Järgmine kord, kui kuulen linnulaulu" },
  { id: 'd054', en: "The next time I smell coffee", et: "Järgmine kord, kui tunnen kohvilõhna" },
  { id: 'd055', en: "The next time I boil water", et: "Järgmine kord, kui keedan vett" },
  { id: 'd056', en: "The next time I set a timer", et: "Järgmine kord, kui panen taimeri" },
  { id: 'd057', en: "The next time I touch a doorknob", et: "Järgmine kord, kui puudutan uksekäepidet" },
  { id: 'd058', en: "The next time I lock a door", et: "Järgmine kord, kui lukustan ukse" },
  { id: 'd059', en: "The next time I adjust the volume", et: "Järgmine kord, kui reguleerin helitugevust" },
  { id: 'd060', en: "The next time I put on headphones", et: "Järgmine kord, kui panen kõrvaklapid pähe" },
  { id: 'd061', en: "The next time I take off headphones", et: "Järgmine kord, kui võtan kõrvaklapid peast" },
  { id: 'd062', en: "The next time I sign my name", et: "Järgmine kord, kui kirjutan oma nime" },
  { id: 'd063', en: "The next time I send a message", et: "Järgmine kord, kui saadan sõnumi" },
  { id: 'd064', en: "The next time I receive a message", et: "Järgmine kord, kui saan sõnumi" },
  { id: 'd065', en: "The next time I scroll to the bottom of a page", et: "Järgmine kord, kui kerin lehe lõppu" },
  { id: 'd066', en: "The next time I scroll to the top", et: "Järgmine kord, kui kerin lehe algusesse" },
  { id: 'd067', en: "The next time I bookmark a page", et: "Järgmine kord, kui lisan lehe järjehoidjatesse" },
  { id: 'd068', en: "The next time I like a post", et: "Järgmine kord, kui laigin postitust" },
  { id: 'd069', en: "The next time I see a stop sign", et: "Järgmine kord, kui näen stoppmärki" },
  { id: 'd070', en: "The next time I cross a street", et: "Järgmine kord, kui ületan tänavat" },
  { id: 'd071', en: "The next time I wash a dish", et: "Järgmine kord, kui pesen nõu" },
  { id: 'd072', en: "The next time I turn a page", et: "Järgmine kord, kui keeran lehte" },
  { id: 'd073', en: "The next time I see a cloud shaped like something", et: "Järgmine kord, kui näen millegi kujuga pilve" },
  { id: 'd074', en: "The next time I put on shoes", et: "Järgmine kord, kui panen jalanõud jalga" },
  { id: 'd075', en: "The next time I take off shoes", et: "Järgmine kord, kui võtan jalanõud ära" },
  { id: 'd076', en: "The next time I zip a zipper", et: "Järgmine kord, kui tõmban luku kinni" },
  { id: 'd077', en: "The next time I button a button", et: "Järgmine kord, kui kinnitan nööbi" },
  { id: 'd078', en: "The next time I tie a knot", et: "Järgmine kord, kui seon sõlme" },
  { id: 'd079', en: "The next time I fold laundry", et: "Järgmine kord, kui voltin pesu" },
  { id: 'd080', en: "The next time I hang a towel", et: "Järgmine kord, kui riputan rätiku" },
  { id: 'd081', en: "The next time I water a plant", et: "Järgmine kord, kui kastan taime" },
  { id: 'd082', en: "The next time I see a house number", et: "Järgmine kord, kui näen majanumbrit" },
  { id: 'd083', en: "The next time I hear a notification chime", et: "Järgmine kord, kui kuulen teavituse heli" },
  { id: 'd084', en: "The next time I open the fridge", et: "Järgmine kord, kui avan külmkapi" },
  { id: 'd085', en: "The next time I close the fridge", et: "Järgmine kord, kui sulgen külmkapi" },
  { id: 'd086', en: "The next time I preheat the oven", et: "Järgmine kord, kui soojendan ahju" },
  { id: 'd087', en: "The next time I take out the trash", et: "Järgmine kord, kui viin prügi välja" },
  { id: 'd088', en: "The next time I recycle something", et: "Järgmine kord, kui taaskasutan midagi" },
  { id: 'd089', en: "The next time I use a password", et: "Järgmine kord, kui kasutan parooli" },
  { id: 'd090', en: "The next time I plug in a charger", et: "Järgmine kord, kui ühendan laadija" },
  { id: 'd091', en: "The next time I unmute the sound", et: "Järgmine kord, kui võtan heli summutusest" },
  { id: 'd092', en: "The next time I mute the sound", et: "Järgmine kord, kui summutan heli" },
  { id: 'd093', en: "The next time I take a screenshot", et: "Järgmine kord, kui teen ekraanipildi" },
  { id: 'd094', en: "The next time I copy text", et: "Järgmine kord, kui kopeerin teksti" },
  { id: 'd095', en: "The next time I paste text", et: "Järgmine kord, kui kleebin teksti" },
  { id: 'd096', en: "The next time I rename a file", et: "Järgmine kord, kui nimetan faili ümber" },
  { id: 'd097', en: "The next time I create a folder", et: "Järgmine kord, kui loon kausta" },
  { id: 'd098', en: "The next time I open settings", et: "Järgmine kord, kui avan seaded" },
  { id: 'd099', en: "The next time I check the weather", et: "Järgmine kord, kui vaatan ilma" },
  { id: 'd100', en: "The next time I see a calendar", et: "Järgmine kord, kui näen kalendrit" },
  { id: 'd101', en: "The next time I hear an alarm", et: "Järgmine kord, kui kuulen äratust" },
  { id: 'd102', en: "The next time I flip a light switch", et: "Järgmine kord, kui vajutan valguslülitit" },
  { id: 'd103', en: "The next time I look at the sky", et: "Järgmine kord, kui vaatan taevast" }
];
